exports.LOADINGSTART = 'LOADINGSTART';
exports.LOADINGEND = 'LOADINGEND';

exports.GETBLOCK = 'GETBLOCK';
exports.GETBLOCKCOUNT = 'GETBLOCKCOUNT';
exports.GETBLOCKHASH = 'GETBLOCKHASH';
exports.GETBESTBLOCKHASH = 'GETBESTBLOCKHASH';
exports.GETCONNECTIONCOUNT = 'GETCONNECTIONCOUNT';
exports.GETBLOCKCHAININFO = 'GETBLOCKCHAININFO';
exports.GETMININGINFO = 'GETMININGINFO';
exports.GETPEERINFO = 'GETPEERINFO';

exports.SETBLOCK = 'SETBLOCK';
exports.SETSELECTEDBLOCK = 'SETSELECTEDBLOCK';
exports.SETSELECTEDBLOCKHEIGHT = 'SETSELECTEDBLOCKHEIGHT';
exports.SETBESTBLOCK = 'SETBESTBLOCK';
exports.SETTRANSACTION = 'SETTRANSACTION';
exports.SETBLOCKS = 'SETBLOCKS';
exports.SETBLOCKLIST = 'SETBLOCKLIST';
exports.SETBLOCKCOUNT = 'SETBLOCKCOUNT';
exports.SETBLOCKHASH = 'SETBLOCKHASH';
exports.SETBESTBLOCKHASH = 'SETBESTBLOCKHASH';
exports.SETCONNECTIONCOUNT = 'SETCONNECTIONCOUNT';
exports.SETBLOCKCHAININFO = 'SETBLOCKCHAININFO';
exports.SETMININGINFO = 'SETMININGINFO';
exports.SETPEERINFO = 'SETPEERINFO';