export const LOADINGSTART = 'LOADINGSTART';
export const LOADINGEND = 'LOADINGEND';

export const GETBLOCKCOUNT = 'GETBLOCKCOUNT';
export const GETBESTBLOCKHASH = 'GETBESTBLOCKHASH';
export const GETCONNECTIONCOUNT = 'GETCONNECTIONCOUNT';
export const GETDIFFICULTY = 'GETDIFFICULTY';
export const GETBLOCKCHAININFO = 'GETBLOCKCHAININFO';
export const GETMININGINFO = 'GETMININGINFO';
export const GETPEERINFO = 'GETPEERINFO';
export const GETRAWMEMPOOL = 'GETRAWMEMPOOL';

export const SETBLOCKCOUNT = 'SETBLOCKCOUNT';
export const SETBESTBLOCKHASH = 'SETBESTBLOCKHASH';
export const SETCONNECTIONCOUNT = 'SETCONNECTIONCOUNT';
export const SETDIFFICULTY = 'SETDIFFICULTY';
export const SETBLOCKCHAININFO = 'SETBLOCKCHAININFO';
export const SETMININGINFO = 'SETMININGINFO';
export const SETPEERINFO = 'SETPEERINFO';
export const SETRAWMEMPOOL = 'SETRAWMEMPOOL';