/* Palette generated by Material Palette - materialpalette.com/blue/pink */

const primaryDark = '#1976D2';
const primaryMain = '#1976D2';
const primaryLight = '#1975d215;';
const secondaryMain = '#FF4081';
const white = '#FFFFFF';
const textPrimary ='#212121';
const textSecondary = '#757575';
const divider = '#BDBDBD';
const fafafa = '#fafafa';
const f5f5f5 = '#f5f5f5';
const dddddd = '#dddddd';
const _00000015 = 'rgba(0,0,0,0.15)';

export const palette = {
    primary: {
        dark: primaryDark,
        main: primaryMain,
        light: primaryLight
    },
    secondary: {
        main: secondaryMain
    },
    text: {
        primary: textPrimary,
        secondary: textSecondary,
        icons: white
    },
    divider: divider,
    grays: {
        fafafa: fafafa,
        f5f5f5: f5f5f5,
        dddddd: dddddd,
        _00000015: _00000015
    },
    background: {
        body: fafafa,
        white: white
    }
};