/* Palette generated by Material Palette - materialpalette.com/blue/pink */

const primaryDark = '#1976D2';
const primaryMain = '#2196F3';
const primaryLight = '#BBDEFB';
const secondaryMain = '#FF4081';
const white = '#FFFFFF';
const textPrimary ='#212121';
const textSecondary = '#757575';
const divider = '#BDBDBD';
const fafafa = '#FAFAFA';

export const palette = {
    primary: {
        dark: primaryDark,
        main: primaryDark,
        light: primaryLight
    },
    secondary: {
        main: secondaryMain
    },
    text: {
        primary: textPrimary,
        secondary: textSecondary,
        icons: white
    },
    divider: divider,
    background: {
        body: fafafa,
        white: white
    }
};